/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface QueryParamsDto {
    offset: number;
    limit: number;
}
export type Result_2 = {
    __kind__: "Ok";
    Ok: Array<Person>;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result = {
    __kind__: "Ok";
    Ok: number;
} | {
    __kind__: "Err";
    Err: string;
};
export interface PersonCreateDto {
    age: number;
    name: string;
}
export type Result_1 = {
    __kind__: "Ok";
    Ok: Person;
} | {
    __kind__: "Err";
    Err: string;
};
export interface Person {
    id: bigint;
    age: number;
    updated_at: bigint;
    name: string;
    created_at: bigint;
}
export interface PersonUpdateDto {
    id: bigint;
    age?: number;
    name?: string;
}
export interface backendInterface {
    person_count(): Promise<Result>;
    person_create(arg0: PersonCreateDto): Promise<Result_1>;
    person_delete(arg0: bigint): Promise<Result_1>;
    person_get(arg0: bigint): Promise<Result_1>;
    person_query(arg0: QueryParamsDto): Promise<Result_2>;
    person_update(arg0: PersonUpdateDto): Promise<Result_1>;
}
import type { Person as _Person, PersonUpdateDto as _PersonUpdateDto, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async person_count(): Promise<Result> {
        const result = await this.actor.person_count();
        return from_candid_Result_n1(result);
    }
    async person_create(arg0: PersonCreateDto): Promise<Result_1> {
        const result = await this.actor.person_create(arg0);
        return from_candid_Result_1_n3(result);
    }
    async person_delete(arg0: bigint): Promise<Result_1> {
        const result = await this.actor.person_delete(arg0);
        return from_candid_Result_1_n3(result);
    }
    async person_get(arg0: bigint): Promise<Result_1> {
        const result = await this.actor.person_get(arg0);
        return from_candid_Result_1_n3(result);
    }
    async person_query(arg0: QueryParamsDto): Promise<Result_2> {
        const result = await this.actor.person_query(arg0);
        return from_candid_Result_2_n5(result);
    }
    async person_update(arg0: PersonUpdateDto): Promise<Result_1> {
        const result = await this.actor.person_update(to_candid_PersonUpdateDto_n7(arg0));
        return from_candid_Result_1_n3(result);
    }
}
function from_candid_Result_1_n3(value: _Result_1): Result_1 {
    return from_candid_variant_n4(value);
}
function from_candid_Result_2_n5(value: _Result_2): Result_2 {
    return from_candid_variant_n6(value);
}
function from_candid_Result_n1(value: _Result): Result {
    return from_candid_variant_n2(value);
}
function from_candid_variant_n2(value: {
    Ok: number;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: number;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n4(value: {
    Ok: _Person;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Person;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n6(value: {
    Ok: Array<_Person>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<Person>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function to_candid_PersonUpdateDto_n7(value: PersonUpdateDto): _PersonUpdateDto {
    return to_candid_record_n8(value);
}
function to_candid_record_n8(value: {
    id: bigint;
    age?: number;
    name?: string;
}): {
    id: bigint;
    age: [] | [number];
    name: [] | [string];
} {
    return {
        id: value.id,
        age: value.age ? candid_some(value.age) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor);
}
