/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AddPersonImport } from './routes/add-person'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const AddPersonRoute = AddPersonImport.update({
  id: '/add-person',
  path: '/add-person',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/add-person': {
      id: '/add-person'
      path: '/add-person'
      fullPath: '/add-person'
      preLoaderRoute: typeof AddPersonImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-person': typeof AddPersonRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-person': typeof AddPersonRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/add-person': typeof AddPersonRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add-person'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-person'
  id: '__root__' | '/' | '/add-person'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddPersonRoute: typeof AddPersonRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddPersonRoute: AddPersonRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/add-person"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/add-person": {
      "filePath": "add-person.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
