/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Person {
  'id' : bigint,
  'age' : number,
  'updated_at' : bigint,
  'name' : string,
  'created_at' : bigint,
}
export interface PersonCreateDto { 'age' : number, 'name' : string }
export interface PersonUpdateDto {
  'id' : bigint,
  'age' : [] | [number],
  'name' : [] | [string],
}
export interface QueryParamsDto { 'offset' : number, 'limit' : number }
export type Result = { 'Ok' : number } |
  { 'Err' : string };
export type Result_1 = { 'Ok' : Person } |
  { 'Err' : string };
export type Result_2 = { 'Ok' : Array<Person> } |
  { 'Err' : string };
export interface _SERVICE {
  'person_count' : ActorMethod<[], Result>,
  'person_create' : ActorMethod<[PersonCreateDto], Result_1>,
  'person_delete' : ActorMethod<[bigint], Result_1>,
  'person_get' : ActorMethod<[bigint], Result_1>,
  'person_query' : ActorMethod<[QueryParamsDto], Result_2>,
  'person_update' : ActorMethod<[PersonUpdateDto], Result_1>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];